version: '3'

services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      ENGINE: DB_ENGINE
      NAME: DB_NAME
      USER: DB_USER
      HOST: DB_HOST
      PORT: DB_PORT
      POSTGRES_PASSWORD: DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    command: python3 manage.py runserver
    ports:
      - '8000:8000'
    depends_on:
      - db
