version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata

  app:
    build: .
    command: python3 manage.py runserver
    ports:
      - '8000:8000'
    depends_on:
      - db
