# Generated by Django 4.2.5 on 2023-09-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак публичности'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_reward',
            field=models.BooleanField(blank=True, null=True, verbose_name='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение'),
        ),
    ]
