# Generated by Django 4.2.5 on 2023-09-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_habits', '0002_alter_habit_is_public_alter_habit_is_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.DurationField(help_text='Time required in seconds', verbose_name='Время на выполнение'),
        ),
    ]
