# Generated by Django 4.2.5 on 2023-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_habits', '0004_alter_habit_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.PositiveIntegerField(max_length=5, verbose_name='Время на выполнение'),
        ),
    ]
