# Generated by Django 4.2.5 on 2023-09-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_habits', '0008_alter_habit_time_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_required',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_required_new',
            field=models.TimeField(blank=True, help_text='Time required', null=True, verbose_name='Время на выполнение'),
        ),
    ]
